version: "3.9"

services:
  quart-app:
    #env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - .env:/app/.env:ro
    ports:
      - "8080:8080"
    environment:
      - DOTENV_PATH=/app/.env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
